import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'in.pranix.edprosys',
  appName: 'EdProSys',
  webDir: 'out',
  server: {
    // Production domain — edprosys.com is live and routes to School OS
    url: 'https://www.edprosys.com',
    cleartext: false,
    androidScheme: 'https',
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 2000,
      backgroundColor: '#1E1B4B',
      androidSplashResourceName: 'splash',
      // Phase 5: iOS splash config uses storyboard (auto-generated by Capacitor)
      iosSpinnerStyle: 'large',
      showSpinner: false,
    },
    StatusBar: {
      style: 'Dark',
      backgroundColor: '#1E1B4B',
    },
    PushNotifications: {
      presentationOptions: ['badge', 'sound', 'alert'],
    },
    Keyboard: {
      // Phase 5: iOS keyboard behavior — resize content so inputs aren't
      // hidden behind the keyboard on iPhone
      resize: 'body',
      resizeOnFullScreen: true,
    },
  },
  android: {
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: false,
  },
  // Phase 5: iOS-specific configuration.
  // The /ios directory is generated by `npx cap add ios` (must be run on a
  // macOS machine with Xcode installed). This config block is pre-defined
  // so the generated project picks up the correct settings immediately.
  ios: {
    // Use School OS URL scheme for deep links (schoolos://)
    scheme: 'SchoolOS',
    // Content inset behavior — 'automatic' respects Safe Area on notched iPhones
    contentInset: 'automatic',
    // Allow inline media playback (needed for any embedded video content)
    allowsLinkPreview: true,
    // Background modes for push notifications
    // (actual entitlements are set in Xcode after `cap add ios`)
  },
};

export default config;
