-- ⚠️ SUPERSEDED MIGRATION — kept as a tombstone, do NOT run.
--
-- The contents originally proposed in PR #10 (current_teacher_staff_id() helper,
-- additive teacher RLS policies, and a test-teacher business-data seed) were
-- applied to production manually via Supabase MCP during the PR #10 → PR #2a
-- handoff, in three pieces:
--
--   1. Master orchestrator applied `item_1_current_teacher_staff_id_helper`
--      at 2026-05-12 02:31 UTC (creates the SECURITY DEFINER helper function).
--   2. Master orchestrator applied the test-teacher seed (auth.users +
--      school_users + staff linkage) via direct SQL the same session.
--   3. Spawn 3 applied `item_1_phase3_additive_teacher_rls` at 2026-05-12
--      02:51 UTC (14 auth_read_teacher / auth_write_teacher / auth_update_teacher
--      policies across 10 tables, all idempotent via DROP IF EXISTS + CREATE).
--
-- This file is retained only so the migration version stays present in git
-- history. supabase_migrations.schema_migrations on prod does NOT have a row
-- for version 20260512020000 — that is intentional and correct.
--
-- See CHANGELOG.md (added in PR #2a) for the full manual-application audit trail.

SELECT 1; -- no-op so a stray apply doesn't fail
